# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UIDVtTmRdqiouyehmJVK1xBu6qRutN4v
"""

# !pip install torch torchvision torchaudio
# !pip install torch-scatter torch-sparse torch-cluster torch-spline-conv -f https://data.pyg.org/whl/torch-$(torch.__version__.split('+')[0]).html
# !pip install torch-geometric

import torch
import torch.nn.functional as F
from torch_geometric.nn import GATConv
from torch_geometric.data import Data
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
import networkx as nx
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA
import pandas as pd
from matplotlib.patches import Patch

# 1. Создание синтетического графа
def create_synthetic_graph(num_nodes=100, num_edges=300):
    """Создание синтетического графа с метками достоверности"""
    G = nx.erdos_renyi_graph(num_nodes, 0.03)
    edge_index = torch.tensor(list(G.edges)).t().contiguous()

    # Признаки узлов: случайные эмбеддинги размерности 16
    x = torch.randn((num_nodes, 16))

    # Метки: 70% достоверных, 30% галлюцинаций
    y = torch.cat([
        torch.ones(int(num_nodes * 0.7), dtype=torch.long),
        torch.zeros(int(num_nodes * 0.3), dtype=torch.long)
    ])
    y = y[torch.randperm(num_nodes)]  # Перемешивание меток

    data = Data(x=x, edge_index=edge_index, y=y)
    return data, G

# 2. Определение модели GNN
class GNNModel(torch.nn.Module):
    def __init__(self, in_channels, hidden_channels, out_channels, heads=4):
        super().__init__()
        self.conv1 = GATConv(in_channels, hidden_channels, heads=heads, dropout=0.6)
        self.conv2 = GATConv(hidden_channels * heads, out_channels, heads=1, concat=False, dropout=0.6)

    def forward(self, data):
        x, edge_index = data.x, data.edge_index
        x = F.dropout(x, p=0.6, training=self.training)
        x = F.elu(self.conv1(x, edge_index))
        x = F.dropout(x, p=0.6, training=self.training)
        x = self.conv2(x, edge_index)
        return F.log_softmax(x, dim=1)

# 3. Обучение модели
def train_model(data, model, optimizer, epochs=200):
    """Обучение модели GNN"""
    model.train()
    train_losses = []
    val_accuracies = []

    for epoch in range(epochs):
        optimizer.zero_grad()
        out = model(data)
        loss = F.nll_loss(out[data.train_mask], data.y[data.train_mask])
        loss.backward()
        optimizer.step()

        if epoch % 20 == 0:
            model.eval()
            with torch.no_grad():
                val_out = model(data)
                val_pred = val_out[data.val_mask].argmax(dim=1)
                val_acc = (val_pred == data.y[data.val_mask]).sum().item() / data.val_mask.size(0)
            model.train()

            train_losses.append(loss.item())
            val_accuracies.append(val_acc)
            print(f'Эпоха {epoch}, Потери: {loss.item():.4f}, Точность на валидации: {val_acc:.4f}')

    return model, train_losses, val_accuracies

# 4. Оценка модели
def evaluate_model(model, data, mask):
    """Оценка производительности модели"""
    model.eval()
    with torch.no_grad():
        out = model(data)
        pred = out.argmax(dim=1)
        pred_proba = torch.exp(out)  # Преобразуем из log_softmax в вероятности
        y_true = data.y[mask].cpu().numpy()
        y_pred = pred[mask].cpu().numpy()
        y_proba = pred_proba[mask].cpu().numpy()

        acc = accuracy_score(y_true, y_pred)
        prec = precision_score(y_true, y_pred, zero_division=0)
        rec = recall_score(y_true, y_pred, zero_division=0)
        f1 = f1_score(y_true, y_pred, zero_division=0)

    return acc, prec, rec, f1, y_true, y_pred, y_proba

# 5. Визуализации
def plot_training_history(train_losses, val_accuracies):
    """Визуализация процесса обучения"""
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))

    # График потерь
    ax1.plot(range(0, 200, 20), train_losses, 'b-', linewidth=2, marker='o')
    ax1.set_xlabel('Эпоха')
    ax1.set_ylabel('Потери при обучении')
    ax1.set_title('Динамика потерь при обучении')
    ax1.grid(True, alpha=0.3)

    # График точности
    ax2.plot(range(0, 200, 20), val_accuracies, 'g-', linewidth=2, marker='s')
    ax2.set_xlabel('Эпоха')
    ax2.set_ylabel('Точность на валидации')
    ax2.set_title('Динамика точности на валидации')
    ax2.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.show()

def plot_confusion_matrix(y_true, y_pred, class_names=['Галлюцинация', 'Факт']):
    """Визуализация матрицы ошибок"""
    cm = confusion_matrix(y_true, y_pred)

    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=class_names,
                yticklabels=class_names)
    plt.xlabel('Предсказанный класс')
    plt.ylabel('Истинный класс')
    plt.title('Матрица ошибок')
    plt.show()

    # Выводим метрики по классам
    print("\nОтчет по классификации:")
    print(classification_report(y_true, y_pred, target_names=class_names))

def plot_node_embeddings(data, model, mask, title="Визуализация векторных представлений узлов"):
    """Визуализация эмбеддингов узлов"""
    model.eval()
    with torch.no_grad():
        # Получаем предпоследние скрытые представления
        x, edge_index = data.x, data.edge_index
        x = model.conv1(x, edge_index)
        x = F.elu(x)
        embeddings = model.conv2(x, edge_index).cpu().numpy()

        # Уменьшаем размерность до 2D для визуализации
        pca = PCA(n_components=2)
        embeddings_2d = pca.fit_transform(embeddings[mask.cpu().numpy()])

        # Цвета по истинным меткам
        y_true = data.y[mask].cpu().numpy()

        plt.figure(figsize=(10, 8))
        scatter = plt.scatter(embeddings_2d[:, 0], embeddings_2d[:, 1],
                            c=y_true, cmap='coolwarm', s=50, alpha=0.7,
                            edgecolors='w', linewidth=0.5)

        plt.colorbar(scatter, label='Класс (0=Галлюцинация, 1=Факт)')
        plt.xlabel('PCA Компонента 1')
        plt.ylabel('PCA Компонента 2')
        plt.title(f'{title}\nОбъясненная дисперсия: {pca.explained_variance_ratio_.sum():.2%}')
        plt.grid(True, alpha=0.3)
        plt.show()

def plot_prediction_distribution(y_proba, y_true):
    """Распределение вероятностей предсказаний"""
    plt.figure(figsize=(10, 6))

    # Разделяем по классам
    hallucination_proba = y_proba[y_true == 0][:, 0]  # Вероятность класса 0
    fact_proba = y_proba[y_true == 1][:, 1]  # Вероятность класса 1

    plt.hist(hallucination_proba, bins=20, alpha=0.5, label='Галлюцинации', color='red')
    plt.hist(fact_proba, bins=20, alpha=0.5, label='Факты', color='blue')

    plt.xlabel('Вероятность предсказания')
    plt.ylabel('Количество')
    plt.title('Распределение вероятностей предсказаний по истинным классам')
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.show()

def plot_network_structure(G, y_pred, title="Структура графа с предсказаниями"):
    """Визуализация структуры графа с предсказаниями"""
    plt.figure(figsize=(12, 10))

    # Позиции узлов
    pos = nx.spring_layout(G, seed=42)

    # Получаем узлы графа
    nodes = list(G.nodes())

    # Создаем цвета для узлов
    node_colors = ['red' if y_pred[node] == 0 else 'green' for node in nodes]

    # Размеры узлов (можно сделать зависимыми от степени)
    node_sizes = [300 + 50 * G.degree(node) for node in nodes]

    # Рисуем граф
    nx.draw_networkx_nodes(G, pos, node_color=node_colors,
                          node_size=node_sizes, alpha=0.8)
    nx.draw_networkx_edges(G, pos, alpha=0.2)

    # Легенда
    legend_elements = [
        Patch(facecolor='red', alpha=0.8, label='Предсказана галлюцинация'),
        Patch(facecolor='green', alpha=0.8, label='Предсказан факт')
    ]

    plt.legend(handles=legend_elements, loc='upper right')
    plt.title(title)
    plt.axis('off')
    plt.tight_layout()
    plt.show()

def plot_metrics_comparison(metrics_dict):
    """Сравнение метрик на разных наборах данных"""
    metrics_df = pd.DataFrame(metrics_dict).T

    fig, axes = plt.subplots(2, 2, figsize=(12, 10))
    metrics = ['Точность', 'Precision', 'Recall', 'F1-Score']

    for idx, metric in enumerate(metrics):
        ax = axes[idx // 2, idx % 2]
        bars = ax.bar(range(len(metrics_df)), metrics_df[metric].values)
        ax.set_xlabel('Набор данных')
        ax.set_ylabel(metric)
        ax.set_title(f'Сравнение {metric}')
        ax.set_xticks(range(len(metrics_df)))
        ax.set_xticklabels(metrics_df.index)

        # Добавляем значения на столбцы
        for bar, val in zip(bars, metrics_df[metric].values):
            ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.01,
                   f'{val:.3f}', ha='center', va='bottom')

    plt.tight_layout()
    plt.show()

# 6. Основной пайплайн
def main():
    # Создание графа
    data, G = create_synthetic_graph(num_nodes=200, num_edges=400)

    # Разделение на train/val/test
    indices = torch.randperm(data.num_nodes)
    data.train_mask = indices[:140]
    data.val_mask = indices[140:170]
    data.test_mask = indices[170:]

    print("="*60)
    print("ИНФОРМАЦИЯ О НАБОРЕ ДАННЫХ")
    print("="*60)
    print(f"Тип y: {data.y.dtype}")
    print(f"Размерность y: {data.y.shape}")
    print(f"Количество узлов: {data.num_nodes}")
    print(f"Количество ребер: {data.edge_index.shape[1]}")
    print(f"Размер обучающей выборки: {data.train_mask.size(0)}")
    print(f"Размер валидационной выборки: {data.val_mask.size(0)}")
    print(f"Размер тестовой выборки: {data.test_mask.size(0)}")

    print(f"\nРаспределение классов:")
    for split, mask in [("Обучающая", data.train_mask),
                       ("Валидационная", data.val_mask),
                       ("Тестовая", data.test_mask)]:
        unique, counts = np.unique(data.y[mask].numpy(), return_counts=True)
        print(f"{split}: Класс 0 (Галлюцинации)={counts[0]}, Класс 1 (Факты)={counts[1]}")

    print("\n" + "="*60)
    print("ОБУЧЕНИЕ МОДЕЛИ")
    print("="*60)

    # Инициализация модели
    model = GNNModel(in_channels=16, hidden_channels=8, out_channels=2, heads=4)
    optimizer = torch.optim.Adam(model.parameters(), lr=0.01, weight_decay=5e-4)

    # Обучение
    model, train_losses, val_accuracies = train_model(data, model, optimizer, epochs=200)

    # Оценка на разных наборах данных
    print("\n" + "="*60)
    print("ОЦЕНКА МОДЕЛИ")
    print("="*60)

    # Получаем все предсказания
    model.eval()
    with torch.no_grad():
        out = model(data)
        all_pred = out.argmax(dim=1).cpu().numpy()

    metrics_dict = {}
    for split_name, mask in [("Обучающая", data.train_mask),
                           ("Валидационная", data.val_mask),
                           ("Тестовая", data.test_mask)]:
        acc, prec, rec, f1, y_true, y_pred, y_proba = evaluate_model(model, data, mask)
        metrics_dict[split_name] = {
            'Точность': acc,
            'Precision': prec,
            'Recall': rec,
            'F1-Score': f1
        }

        if split_name == "Тестовая":  # Сохраняем для визуализаций
            test_y_true, test_y_pred, test_y_proba = y_true, y_pred, y_proba

        print(f"\nРезультаты на {split_name.lower()} выборке:")
        print(f"Точность: {acc:.4f}, Precision: {prec:.4f}, Recall: {rec:.4f}, F1-Score: {f1:.4f}")

    # ВИЗУАЛИЗАЦИИ
    print("\n" + "="*60)
    print("ВИЗУАЛИЗАЦИИ")
    print("="*60)

    # 1. История обучения
    print("\n1. Визуализация истории обучения:")
    plot_training_history(train_losses, val_accuracies)

    # 2. Визуализация эмбеддингов
    print("\n3. Визуализация векторных представлений (тестовая выборка):")
    plot_node_embeddings(data, model, data.test_mask, "Векторные представления тестовой выборки")

    # 3. Распределение вероятностей
    print("\n4. Распределение вероятностей предсказаний (тестовая выборка):")
    plot_prediction_distribution(test_y_proba, test_y_true)

    # 4. Структура графа с предсказаниями
    print("\n5. Структура графа с предсказаниями:")

    # Создаем подграф для первых 50 узлов
    nodes_subset = list(range(min(50, len(G.nodes()))))
    G_subset = G.subgraph(nodes_subset)

    # Получаем предсказания для этих узлов
    y_pred_subset = all_pred[nodes_subset]

    plot_network_structure(G_subset, y_pred_subset,
                          "Структура графа (первые 50 узлов)")

    # 6. Сравнение метрик
    print("\n6. Сравнение метрик на разных наборах данных:")
    plot_metrics_comparison(metrics_dict)

    # Дополнительный анализ
    print("\n" + "="*60)
    print("ДОПОЛНИТЕЛЬНЫЙ АНАЛИЗ")
    print("="*60)

    # Анализ уверенности модели
    confidence_scores = np.max(test_y_proba, axis=1)
    print(f"\nАнализ уверенности модели (тестовая выборка):")
    print(f"Средняя уверенность: {confidence_scores.mean():.4f}")
    print(f"Стандартное отклонение уверенности: {confidence_scores.std():.4f}")
    print(f"Минимальная уверенность: {confidence_scores.min():.4f}")
    print(f"Максимальная уверенность: {confidence_scores.max():.4f}")

    # Анализ ошибок
    errors = test_y_true != test_y_pred
    if errors.any():
        print(f"\nАнализ ошибок:")
        print(f"Количество ошибок: {errors.sum()}")
        print(f"Доля ошибок: {errors.sum()/len(errors):.4f}")

        error_confidences = confidence_scores[errors]
        correct_confidences = confidence_scores[~errors]
        print(f"Средняя уверенность на ошибочных предсказаниях: {error_confidences.mean():.4f}")
        print(f"Средняя уверенность на правильных предсказаниях: {correct_confidences.mean():.4f}")

    # Анализ связности
    print(f"\nАнализ связности графа:")
    print(f"Количество связных компонент: {nx.number_connected_components(G)}")

    # Анализ степени узлов по классам
    degrees = dict(G.degree())
    hallucination_nodes = [i for i in range(len(all_pred)) if all_pred[i] == 0]
    fact_nodes = [i for i in range(len(all_pred)) if all_pred[i] == 1]

    if hallucination_nodes:
        hallucination_degrees = [degrees[i] for i in hallucination_nodes]
        print(f"Средняя степень узлов с предсказанными галлюцинациями: {np.mean(hallucination_degrees):.2f}")

    if fact_nodes:
        fact_degrees = [degrees[i] for i in fact_nodes]
        print(f"Средняя степень узлов с предсказанными фактами: {np.mean(fact_degrees):.2f}")

if __name__ == '__main__':
    main()